-- Patch untuk database albarakah yang sudah pernah dibuat.
-- Jalankan setelah backup data jika tidak ingin import ulang database/schema.sql.

USE albarakah;

ALTER TABLE T_SETORAN MODIFY ID_TABUNGAN INT NULL;

CREATE TABLE IF NOT EXISTS T_PEMBAYARAN (
  ID_PEMBAYARAN INT AUTO_INCREMENT PRIMARY KEY,
  ID_PESANAN    INT NULL,
  ID_SETORAN    INT NULL,
  NOMINAL       DECIMAL(15,2) NOT NULL,
  METODE        VARCHAR(30) NOT NULL,
  STATUS        VARCHAR(30) NOT NULL DEFAULT 'Menunggu Pembayaran',
  REF_BAYAR     VARCHAR(100),
  TGL_BAYAR     DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS T_LAPORAN_KEUANGAN (
  ID_LAPORAN      INT AUTO_INCREMENT PRIMARY KEY,
  PERIODE_TANGGAL DATE NOT NULL,
  PEMASUKAN       DECIMAL(15,2) NOT NULL DEFAULT 0,
  PENGELUARAN     DECIMAL(15,2) NOT NULL DEFAULT 0,
  LABA_RUGI       DECIMAL(15,2) NOT NULL DEFAULT 0,
  CATATAN         TEXT,
  TGL_BUAT        DATETIME NOT NULL DEFAULT NOW()
);

DELIMITER //
CREATE PROCEDURE add_column_if_missing(
  IN table_name_in VARCHAR(64),
  IN column_name_in VARCHAR(64),
  IN ddl_in TEXT
)
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = table_name_in
      AND COLUMN_NAME = column_name_in
  ) THEN
    SET @ddl = ddl_in;
    PREPARE stmt FROM @ddl;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
  END IF;
END//
DELIMITER ;

CALL add_column_if_missing('T_TABUNGAN_QURBAN', 'ID_HEWAN', 'ALTER TABLE T_TABUNGAN_QURBAN ADD COLUMN ID_HEWAN INT NULL AFTER TARGET_NOMINAL');
CALL add_column_if_missing('T_TABUNGAN_QURBAN', 'ID_PESANAN', 'ALTER TABLE T_TABUNGAN_QURBAN ADD COLUMN ID_PESANAN INT NULL AFTER ID_HEWAN');
CALL add_column_if_missing('T_SETORAN', 'ID_PESANAN', 'ALTER TABLE T_SETORAN ADD COLUMN ID_PESANAN INT NULL AFTER ID_TABUNGAN');
CALL add_column_if_missing('T_SETORAN', 'REF_BAYAR', 'ALTER TABLE T_SETORAN ADD COLUMN REF_BAYAR VARCHAR(100) NULL AFTER STATUS');
CALL add_column_if_missing('T_PELANGGAN', 'ROLE', 'ALTER TABLE T_PELANGGAN ADD COLUMN ROLE ENUM(''PELANGGAN'',''ADMIN'') NOT NULL DEFAULT ''PELANGGAN'' AFTER NO_HP');

DROP PROCEDURE add_column_if_missing;

CREATE TABLE IF NOT EXISTS T_JADWAL_PEMOTONGAN (
  ID_JADWAL INT AUTO_INCREMENT PRIMARY KEY,
  TANGGAL   DATE NOT NULL,
  TEMPAT    VARCHAR(200) NOT NULL,
  KUOTA     INT NOT NULL DEFAULT 0,
  STATUS    CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE IF NOT EXISTS T_PATUNGAN_QURBAN (
  ID_PATUNGAN          INT AUTO_INCREMENT PRIMARY KEY,
  ID_PESANAN           INT NOT NULL,
  ID_PEMINTA           INT NOT NULL,
  ID_PELANGGAN_TUJUAN  INT NULL,
  EMAIL_TUJUAN         VARCHAR(150) NOT NULL,
  NOMINAL_PORSI        DECIMAL(15,2) NOT NULL DEFAULT 0,
  STATUS               ENUM('MENUNGGU','DISETUJUI','DITOLAK') NOT NULL DEFAULT 'MENUNGGU',
  TGL_BUAT             DATETIME NOT NULL DEFAULT NOW(),
  TGL_RESPON           DATETIME NULL
);

INSERT INTO T_JADWAL_PEMOTONGAN (TANGGAL, TEMPAT, KUOTA)
SELECT * FROM (
  SELECT DATE('2026-06-17') AS TANGGAL, 'Peternakan Pusat Al-Barakah' AS TEMPAT, 20 AS KUOTA
  UNION ALL SELECT DATE('2026-06-18'), 'Masjid Al-Ikhlas', 12
  UNION ALL SELECT DATE('2026-06-19'), 'Peternakan Cabang', 15
) seed
WHERE NOT EXISTS (SELECT 1 FROM T_JADWAL_PEMOTONGAN LIMIT 1);

DROP VIEW IF EXISTS V_PESANAN_LENGKAP;
CREATE VIEW V_PESANAN_LENGKAP AS
  SELECT
    p.*,
    detail.NAMA_HEWAN,
    COALESCE(setoran.TOTAL_SETORAN, 0) AS TOTAL_SETORAN,
    COALESCE(bayar.TOTAL_PEMBAYARAN, 0) AS TOTAL_PEMBAYARAN,
    CASE
      WHEN COALESCE(setoran.TOTAL_SETORAN, 0) > 0 THEN COALESCE(setoran.TOTAL_SETORAN, 0)
      ELSE COALESCE(bayar.TOTAL_PEMBAYARAN, 0)
    END AS TOTAL_DIBAYAR,
    GREATEST(
      p.TOTAL - CASE
        WHEN COALESCE(setoran.TOTAL_SETORAN, 0) > 0 THEN COALESCE(setoran.TOTAL_SETORAN, 0)
        ELSE COALESCE(bayar.TOTAL_PEMBAYARAN, 0)
      END,
      0
    ) AS SISA_BAYAR
  FROM T_PESANAN p
  LEFT JOIN (
    SELECT
      d.ID_PESANAN,
      GROUP_CONCAT(CONCAT(h.NAMA, ' x', d.JUMLAH) ORDER BY d.ID_DETAIL SEPARATOR ', ') AS NAMA_HEWAN
    FROM T_DETAIL_PESANAN d
    JOIN T_HEWAN h ON h.ID_HEWAN = d.ID_HEWAN
    GROUP BY d.ID_PESANAN
  ) detail ON detail.ID_PESANAN = p.ID_PESANAN
  LEFT JOIN (
    SELECT ID_PESANAN, SUM(NOMINAL) AS TOTAL_SETORAN
    FROM T_SETORAN
    WHERE STATUS = 'LUNAS' AND ID_PESANAN IS NOT NULL
    GROUP BY ID_PESANAN
  ) setoran ON setoran.ID_PESANAN = p.ID_PESANAN
  LEFT JOIN (
    SELECT ID_PESANAN, SUM(NOMINAL) AS TOTAL_PEMBAYARAN
    FROM T_PEMBAYARAN
    WHERE STATUS = 'LUNAS' AND ID_SETORAN IS NULL AND ID_PESANAN IS NOT NULL
    GROUP BY ID_PESANAN
  ) bayar ON bayar.ID_PESANAN = p.ID_PESANAN;

DROP VIEW IF EXISTS V_LAPORAN_KEUANGAN_HARIAN;
CREATE VIEW V_LAPORAN_KEUANGAN_HARIAN AS
  SELECT
    DATE(TGL_BAYAR) AS PERIODE_TANGGAL,
    SUM(CASE WHEN STATUS = 'LUNAS' THEN NOMINAL ELSE 0 END) AS PEMASUKAN,
    0 AS PENGELUARAN,
    SUM(CASE WHEN STATUS = 'LUNAS' THEN NOMINAL ELSE 0 END) AS LABA_RUGI
  FROM T_PEMBAYARAN
  GROUP BY DATE(TGL_BAYAR);
