-- ============================================================
--  Al-Barakah Aqiqah & Qurban - MySQL Schema (XAMPP)
-- ============================================================
CREATE DATABASE IF NOT EXISTS albarakah CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE albarakah;

SET FOREIGN_KEY_CHECKS = 0;

DROP VIEW IF EXISTS V_LAPORAN_KEUANGAN_HARIAN;
DROP VIEW IF EXISTS V_PESANAN_LENGKAP;
DROP VIEW IF EXISTS V_STOK_HEWAN;

DROP TABLE IF EXISTS T_LAPORAN_KEUANGAN;
DROP TABLE IF EXISTS T_PATUNGAN_QURBAN;
DROP TABLE IF EXISTS T_JADWAL_PEMOTONGAN;
DROP TABLE IF EXISTS T_PEMBAYARAN;
DROP TABLE IF EXISTS T_SETORAN;
DROP TABLE IF EXISTS T_TABUNGAN_QURBAN;
DROP TABLE IF EXISTS T_NOTIFIKASI;
DROP TABLE IF EXISTS T_DETAIL_PESANAN;
DROP TABLE IF EXISTS T_PESANAN;
DROP TABLE IF EXISTS T_HEWAN;
DROP TABLE IF EXISTS T_PELANGGAN;

SET FOREIGN_KEY_CHECKS = 1;

-- PELANGGAN
CREATE TABLE T_PELANGGAN (
  ID_PELANGGAN     INT AUTO_INCREMENT PRIMARY KEY,
  NAMA_LENGKAP     VARCHAR(150) NOT NULL,
  EMAIL            VARCHAR(150) NOT NULL UNIQUE,
  PASSWORD_HASH    VARCHAR(255) NOT NULL,
  NO_HP            VARCHAR(20),
  ROLE             ENUM('PELANGGAN','ADMIN') NOT NULL DEFAULT 'PELANGGAN',
  STATUS           CHAR(1)     NOT NULL DEFAULT 'P',
  EMAIL_VERIFIED   TINYINT(1)  NOT NULL DEFAULT 0,
  VERIFY_TOKEN     VARCHAR(100),
  VERIFY_EXPIRES   DATETIME,
  RESET_TOKEN      VARCHAR(100),
  RESET_EXPIRES    DATETIME,
  TGL_DAFTAR       DATETIME    NOT NULL DEFAULT NOW()
);

-- HEWAN / STOK
CREATE TABLE T_HEWAN (
  ID_HEWAN   INT AUTO_INCREMENT PRIMARY KEY,
  JENIS      ENUM('SAPI','KAMBING','DOMBA') NOT NULL,
  NAMA       VARCHAR(150) NOT NULL,
  BERAT_INFO VARCHAR(50),
  HARGA      DECIMAL(15,2) NOT NULL,
  STOK       INT NOT NULL DEFAULT 0,
  GRADE      VARCHAR(5),
  SHARE      INT NOT NULL DEFAULT 1,
  KATEGORI   VARCHAR(30),
  STATUS     CHAR(1) NOT NULL DEFAULT 'A'
);

CREATE VIEW V_STOK_HEWAN AS
  SELECT *
  FROM T_HEWAN
  WHERE STOK > 0 AND STATUS = 'A';

-- PESANAN
CREATE TABLE T_PESANAN (
  ID_PESANAN      INT AUTO_INCREMENT PRIMARY KEY,
  ID_PELANGGAN    INT NOT NULL,
  JENIS_LAYANAN   ENUM('QURBAN','AQIQAH') NOT NULL,
  TGL_PESAN       DATETIME NOT NULL DEFAULT NOW(),
  TGL_PELAKSANAAN DATE,
  ALAMAT_KIRIM    TEXT,
  STATUS          VARCHAR(30) NOT NULL DEFAULT 'Menunggu Konfirmasi',
  TOTAL           DECIMAL(15,2) NOT NULL DEFAULT 0,
  METODE_BAYAR    VARCHAR(30),
  CONSTRAINT FK_PESANAN_PELANGGAN
    FOREIGN KEY (ID_PELANGGAN) REFERENCES T_PELANGGAN(ID_PELANGGAN)
    ON UPDATE CASCADE
);

CREATE TABLE T_DETAIL_PESANAN (
  ID_DETAIL    INT AUTO_INCREMENT PRIMARY KEY,
  ID_PESANAN   INT NOT NULL,
  ID_HEWAN     INT NOT NULL,
  JUMLAH       INT NOT NULL DEFAULT 1,
  HARGA_SATUAN DECIMAL(15,2) NOT NULL DEFAULT 0,
  IS_PATUNGAN  CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT FK_DETAIL_PESANAN
    FOREIGN KEY (ID_PESANAN) REFERENCES T_PESANAN(ID_PESANAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_DETAIL_HEWAN
    FOREIGN KEY (ID_HEWAN) REFERENCES T_HEWAN(ID_HEWAN)
    ON UPDATE CASCADE
);

CREATE TABLE T_JADWAL_PEMOTONGAN (
  ID_JADWAL INT AUTO_INCREMENT PRIMARY KEY,
  TANGGAL   DATE NOT NULL,
  TEMPAT    VARCHAR(200) NOT NULL,
  KUOTA     INT NOT NULL DEFAULT 0,
  STATUS    CHAR(1) NOT NULL DEFAULT 'A'
);

-- TABUNGAN QURBAN
CREATE TABLE T_TABUNGAN_QURBAN (
  ID_TABUNGAN    INT AUTO_INCREMENT PRIMARY KEY,
  ID_PELANGGAN   INT NOT NULL,
  NAMA_TABUNGAN  VARCHAR(150),
  JENIS_TARGET   ENUM('SAPI','KAMBING','DOMBA') NOT NULL DEFAULT 'KAMBING',
  TARGET_NOMINAL DECIMAL(15,2) NOT NULL DEFAULT 0,
  ID_HEWAN       INT NULL,
  ID_PESANAN     INT NULL,
  TERKUMPUL      DECIMAL(15,2) NOT NULL DEFAULT 0,
  STATUS         CHAR(1) NOT NULL DEFAULT 'A',
  TGL_BUAT       DATETIME NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_TABUNGAN_PELANGGAN
    FOREIGN KEY (ID_PELANGGAN) REFERENCES T_PELANGGAN(ID_PELANGGAN)
    ON UPDATE CASCADE,
  CONSTRAINT FK_TABUNGAN_HEWAN
    FOREIGN KEY (ID_HEWAN) REFERENCES T_HEWAN(ID_HEWAN)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT FK_TABUNGAN_PESANAN
    FOREIGN KEY (ID_PESANAN) REFERENCES T_PESANAN(ID_PESANAN)
    ON DELETE SET NULL ON UPDATE CASCADE
);

-- SETORAN
-- Satu setoran boleh terkait ke tabungan qurban ATAU cicilan pesanan qurban.
CREATE TABLE T_SETORAN (
  ID_SETORAN   INT AUTO_INCREMENT PRIMARY KEY,
  ID_TABUNGAN  INT NULL,
  ID_PESANAN   INT NULL,
  NOMINAL      DECIMAL(15,2) NOT NULL,
  METODE       VARCHAR(30) NOT NULL DEFAULT 'TUNAI',
  STATUS       VARCHAR(30) NOT NULL DEFAULT 'LUNAS',
  REF_BAYAR    VARCHAR(100),
  TGL_SETOR    DATETIME NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_SETORAN_TABUNGAN
    FOREIGN KEY (ID_TABUNGAN) REFERENCES T_TABUNGAN_QURBAN(ID_TABUNGAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SETORAN_PESANAN
    FOREIGN KEY (ID_PESANAN) REFERENCES T_PESANAN(ID_PESANAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT CK_SETORAN_TARGET
    CHECK (
      (ID_TABUNGAN IS NOT NULL AND ID_PESANAN IS NULL)
      OR (ID_TABUNGAN IS NULL AND ID_PESANAN IS NOT NULL)
    )
);

-- PEMBAYARAN
CREATE TABLE T_PEMBAYARAN (
  ID_PEMBAYARAN INT AUTO_INCREMENT PRIMARY KEY,
  ID_PESANAN    INT NULL,
  ID_SETORAN    INT NULL,
  NOMINAL       DECIMAL(15,2) NOT NULL,
  METODE        VARCHAR(30) NOT NULL,
  STATUS        VARCHAR(30) NOT NULL DEFAULT 'Menunggu Pembayaran',
  REF_BAYAR     VARCHAR(100),
  TGL_BAYAR     DATETIME NOT NULL DEFAULT NOW(),
  CONSTRAINT FK_PEMBAYARAN_PESANAN
    FOREIGN KEY (ID_PESANAN) REFERENCES T_PESANAN(ID_PESANAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_PEMBAYARAN_SETORAN
    FOREIGN KEY (ID_SETORAN) REFERENCES T_SETORAN(ID_SETORAN)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE T_PATUNGAN_QURBAN (
  ID_PATUNGAN          INT AUTO_INCREMENT PRIMARY KEY,
  ID_PESANAN           INT NOT NULL,
  ID_PEMINTA           INT NOT NULL,
  ID_PELANGGAN_TUJUAN  INT NULL,
  EMAIL_TUJUAN         VARCHAR(150) NOT NULL,
  NOMINAL_PORSI        DECIMAL(15,2) NOT NULL DEFAULT 0,
  STATUS               ENUM('MENUNGGU','DISETUJUI','DITOLAK') NOT NULL DEFAULT 'MENUNGGU',
  TGL_BUAT             DATETIME NOT NULL DEFAULT NOW(),
  TGL_RESPON           DATETIME NULL,
  CONSTRAINT FK_PATUNGAN_PESANAN
    FOREIGN KEY (ID_PESANAN) REFERENCES T_PESANAN(ID_PESANAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_PATUNGAN_PEMINTA
    FOREIGN KEY (ID_PEMINTA) REFERENCES T_PELANGGAN(ID_PELANGGAN)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_PATUNGAN_TUJUAN
    FOREIGN KEY (ID_PELANGGAN_TUJUAN) REFERENCES T_PELANGGAN(ID_PELANGGAN)
    ON DELETE SET NULL ON UPDATE CASCADE
);

-- NOTIFIKASI
CREATE TABLE T_NOTIFIKASI (
  ID_NOTIFIKASI INT AUTO_INCREMENT PRIMARY KEY,
  ID_PELANGGAN  INT NOT NULL,
  JUDUL         VARCHAR(200),
  PESAN         TEXT,
  TIPE          VARCHAR(20) NOT NULL DEFAULT 'INFO',
  IS_READ       CHAR(1) NOT NULL DEFAULT 'N',
  TGL_KIRIM     DATETIME NOT NULL DEFAULT NOW(),
  TGL_BACA      DATETIME,
  CONSTRAINT FK_NOTIFIKASI_PELANGGAN
    FOREIGN KEY (ID_PELANGGAN) REFERENCES T_PELANGGAN(ID_PELANGGAN)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- LAPORAN KEUANGAN MANUAL
CREATE TABLE T_LAPORAN_KEUANGAN (
  ID_LAPORAN      INT AUTO_INCREMENT PRIMARY KEY,
  PERIODE_TANGGAL DATE NOT NULL,
  PEMASUKAN       DECIMAL(15,2) NOT NULL DEFAULT 0,
  PENGELUARAN     DECIMAL(15,2) NOT NULL DEFAULT 0,
  LABA_RUGI       DECIMAL(15,2) NOT NULL DEFAULT 0,
  CATATAN         TEXT,
  TGL_BUAT        DATETIME NOT NULL DEFAULT NOW()
);

CREATE VIEW V_PESANAN_LENGKAP AS
  SELECT
    p.*,
    detail.NAMA_HEWAN,
    COALESCE(setoran.TOTAL_SETORAN, 0) AS TOTAL_SETORAN,
    COALESCE(bayar.TOTAL_PEMBAYARAN, 0) AS TOTAL_PEMBAYARAN,
    CASE
      WHEN COALESCE(setoran.TOTAL_SETORAN, 0) > 0 THEN COALESCE(setoran.TOTAL_SETORAN, 0)
      ELSE COALESCE(bayar.TOTAL_PEMBAYARAN, 0)
    END AS TOTAL_DIBAYAR,
    GREATEST(
      p.TOTAL - CASE
        WHEN COALESCE(setoran.TOTAL_SETORAN, 0) > 0 THEN COALESCE(setoran.TOTAL_SETORAN, 0)
        ELSE COALESCE(bayar.TOTAL_PEMBAYARAN, 0)
      END,
      0
    ) AS SISA_BAYAR
  FROM T_PESANAN p
  LEFT JOIN (
    SELECT
      d.ID_PESANAN,
      GROUP_CONCAT(CONCAT(h.NAMA, ' x', d.JUMLAH) ORDER BY d.ID_DETAIL SEPARATOR ', ') AS NAMA_HEWAN
    FROM T_DETAIL_PESANAN d
    JOIN T_HEWAN h ON h.ID_HEWAN = d.ID_HEWAN
    GROUP BY d.ID_PESANAN
  ) detail ON detail.ID_PESANAN = p.ID_PESANAN
  LEFT JOIN (
    SELECT ID_PESANAN, SUM(NOMINAL) AS TOTAL_SETORAN
    FROM T_SETORAN
    WHERE STATUS = 'LUNAS' AND ID_PESANAN IS NOT NULL
    GROUP BY ID_PESANAN
  ) setoran ON setoran.ID_PESANAN = p.ID_PESANAN
  LEFT JOIN (
    SELECT ID_PESANAN, SUM(NOMINAL) AS TOTAL_PEMBAYARAN
    FROM T_PEMBAYARAN
    WHERE STATUS = 'LUNAS' AND ID_SETORAN IS NULL AND ID_PESANAN IS NOT NULL
    GROUP BY ID_PESANAN
  ) bayar ON bayar.ID_PESANAN = p.ID_PESANAN;

CREATE VIEW V_LAPORAN_KEUANGAN_HARIAN AS
  SELECT
    DATE(TGL_BAYAR) AS PERIODE_TANGGAL,
    SUM(CASE WHEN STATUS = 'LUNAS' THEN NOMINAL ELSE 0 END) AS PEMASUKAN,
    0 AS PENGELUARAN,
    SUM(CASE WHEN STATUS = 'LUNAS' THEN NOMINAL ELSE 0 END) AS LABA_RUGI
  FROM T_PEMBAYARAN
  GROUP BY DATE(TGL_BAYAR);

-- SEED DATA
INSERT INTO T_HEWAN (JENIS, NAMA, BERAT_INFO, HARGA, STOK, GRADE, SHARE, KATEGORI) VALUES
('SAPI',    'Sapi Limosin Premium', '300-350 kg', 18500000, 12, 'A',  7, 'qurban'),
('SAPI',    'Sapi Simental',        '250-300 kg', 15000000,  8, 'A',  7, 'qurban'),
('SAPI',    'Sapi Brahman',         '200-250 kg', 12000000, 15, 'B',  7, 'qurban'),
('KAMBING', 'Kambing Etawa Jumbo',  '35-45 kg',   3200000,  25, 'A',  1, 'qurban_aqiqah'),
('KAMBING', 'Kambing PE Pilihan',   '30-35 kg',   2800000,  30, 'A',  1, 'qurban_aqiqah'),
('KAMBING', 'Kambing Kacang',       '20-25 kg',   1800000,  40, 'B',  1, 'qurban_aqiqah'),
('DOMBA',   'Domba Garut Premium',  '40-50 kg',   3800000,  18, 'A+', 1, 'aqiqah'),
('DOMBA',   'Domba Ekor Gemuk',     '35-40 kg',   3200000,  22, 'A',  1, 'aqiqah');

INSERT INTO T_JADWAL_PEMOTONGAN (TANGGAL, TEMPAT, KUOTA) VALUES
('2026-06-17', 'Peternakan Pusat Al-Barakah', 20),
('2026-06-18', 'Masjid Al-Ikhlas', 12),
('2026-06-19', 'Peternakan Cabang', 15);
